config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'articles#index'

namespace :api do 
  get '/today_quote' => 'quotes#index'
end
  resources :articles do
    resources :comments
  end
end

  # get '/articles/index'  =>  '/articles#index'
  # get '/articles' => 'articles#index'

  # get '/articles/new' => 'articles#new'
  # post "/articles" => "articles#create"

  # get '/articles/:id/edit' => 'articles#edit'
  # get '/articles/:id' => 'articles#show'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :author, :content, presence: true
    validates :title, presence: true, uniqueness: {scope: 'title', message:'should be unique'}

    has_many :comments
    has_and_belongs_to_many :tags

    before_validation :set_content

    def set_content
        unless self.content
        self.content = 'Default Content'
        end
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content, presence: true

    belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :articles
end

app/controllers/api/quotes_controller.rb
module Api
  class QuotesController < ApplicationController
      def index
          quotes = QuoteRandomizer::Client.today

          render json: quotes
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    
    def index
        @articles = Article.all

        @randomQuote = QuoteRandomizer::Client.today
    end

    def new
        @article = Article.new
    end

    def show
        @comments = @article.comments.where.not(id: nil)
        @comment = @article.comments.build
    end

    def create
        @article = Article.new(article_params) 
        
        if @article.save
            flash[:notice] = "An article has been successfully created"
            redirect_to articles_path
        else
            flash[:error] = 'Error encountered'
            render :new
        end
    end

    def edit
    end
    
    def update
        if @article.update(article_params)
            redirect_to articles_path
        else
            render :edit
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path, notice: "An article was successfully deleted"
    end
    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :author, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_article

    def create
        @comment = @article.comments.build(comment_params) 
        
        if @comment.save
            flash[:notice] = "A comment has been successfully created"
            redirect_to article_path(@article)
        else
            flash[:error] = 'Error encountered'
            @comments = @article.comments.where.not(id: nil)
            render "articles/show"
        end
    end

    def edit
        @comment = @article.comments.find(params[:id])
    end
    
    def update
        @comment = @article.comments.find(params[:id])  

        if @comment.update(comment_params)
            redirect_to article_path(@article)
        else
            flash[:error] = 'Error encountered'
            render :edit
        end
    end

    def destroy
        @comment = @article.comments.find(params[:id])
    
        @comment.destroy
        redirect_to article_path(@article), notice: "A comment was successfully deleted"
    end
    
    private

    def set_article
        @article = Article.find(params[:article_id])
    end

    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.haml
= form_with model: @article do |f|
    = f.label :title
    = f.text_field :title
    %br

    - if f.object.errors[:title].present?
        %span= f.object.errors[:title ].to_sentence

    = f.label :author
    = f.text_field :author
    %br

    - if f.object.errors[:author].present?
        %span= f.object.errors[:author].to_sentence

    = f.label :content
    = f.text_area :content
    %br

    -if f.object.errors[:content].present?
        %span= f.object.errors[:content].to_sentence

    = f.submit 

=  link_to 'Back', articles_path 

app/views/articles/edit.html.erb
<h1> Edit an Article </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1> Hello world</h1>
<p> This is paragraph</p>

<hr/>
<blockquote>
<h4>
<%= @randomQuote[:data]["text"] %>
</h4>
</blockquote>
<hr/>

<table>
    <thead>
        <tr>
        <th> Title </th>
        <th> Author </th>
        <th> Content </th>
        <th> Actions </th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article|%>
            <tr> 
                <td> <%= article.title %> </td>
                <td> <%= article.author %> </td>
                <td> <%= article.content.truncate(50) %> </td>
                <td> 
                <%= link_to article do %>  
                Show
                <% end %>
                <%= link_to edit_article_path(article.id) do %>  
                Edit
                <% end %>
                <%=
                link_to article_path(article.id), method: :delete, data: {confirm: "Sure ka?"} do %>  
                Delete
                <% end %>
                </td>
            </tr>
        <%end%>
    </tbody>
</table>

<%= link_to new_article_path do %>
    New Article
<%end%>

app/views/articles/new.html.erb
<h1> Create an Article </h1>

<%= render 'form' %>

app/views/articles/show.html.haml
%h1= @article.title
%p= @article.author
%p= @article.content

%hr

%table
    %thead
        %th Content
        %th Action 
    %tbody
    - @comments.each do |comment|
        %tr
        %td= comment.content
        %td= link_to 'Edit', edit_article_comment_path(@article.id, comment.id)
        %td= link_to 'Delete', article_comment_path(@article.id, comment.id), method: :delete, data: { confirm: "Are you sure?" } 
= render 'comments/form'

%p= link_to 'Back', articles_path 
%p= link_to 'Delete', article_path(@article.id), method: :delete, data: {confirm: "Sure ka?"}

app/views/comments/_form.html.haml
= form_with model: [@article, @comment] do |f|
    = f.label :content
    = f.text_area :content, placeholder: "Add comment"
    %br
    = f.submit

app/views/comments/edit.html.haml
%h1 Edit a comment
= render 'comments/form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:error] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>